on:
  push:
    branches:
      - master

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '18.x'
      - run: npm ci
      - run: npm run build
      - name: deploy to production
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          password: ${{ secrets.PRODUCTION_PASSWORD }}
          script: |
            cd /var/www/apptest
            git pull origin master
            npm install && npm run build
            pm2 reload all
      
  